syntax = "proto3";

package scheduler;

option go_package = "github.com/jason-mac/job-scheduler/api/internal/schedulerpb;schedulerpb";

service Scheduler
{
  rpc SubmitJob(SubmitJobRequest) returns (SubmitJobResponse);
  rpc ReportJobResult(ReportJobResultRequest) returns (ReportJobResultResponse);
}

message SubmitJobRequest
{
  string command = 1;
  string job_id = 2;
}

message SubmitJobResponse
{
  string response = 1;
}

message ReportJobResultRequest
{
  string job_id = 1;
  int32 exit_code = 2;
}

message ReportJobResultResponse
{
}

service Worker
{
  rpc ExecuteJob(ExecuteJobRequest) returns (ExecuteJobResponse);
}

message ExecuteJobRequest
{
  string command = 1;
  string job_id = 2;
}

message ExecuteJobResponse
{
  string response = 1;
}
